### PR TITLE
Python3 support

### PR DESCRIPTION
**Pull request by Will-wastelander**
Added python3 support. This is related to https://github.com/sn4k3/Octoprint-SDS011/issues/1

### CODE REVIEW

**Comment by sn4k3** [comment]
thanks for the PR

**Comment by Will-wastelander** [comment]
No problem. I also believe that you can use the requirements.txt file to complete the install pre-reqs..

**Comment by Will-wastelander** [comment]
I also have some PMS7003s coming, so I can do some testing with them.

**Comment by sn4k3** [comment]
That would be nice! also if you can compare both would be super...

**Pull request merged**
